### ISSUE TITLE
"Check users content against the CleanTalk antispam service" has no effect

### ISSUE THREAD

**Issue by Sudrien** [CleanTalk/xenforo2-antispam#1]
Since installing version 1.5 on Xenforo 2.0.4, no messages have been been detected as spam, even though several obviously were. 

"Check new registrations against the CleanTalk antispam service" has detected a few spammers, so it seems my server is contacting the cleantalk ones.

( Service #359692, app version 1.5. )

**Comment by ardavydov** [comment]
Hello,

We've answered you via our ticket system.
